### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by zhangyi2017** [dcy421/activiti6-modeler-demo#1]
发现咱们中国人做事真的不认真，下载完demo按照 readme步骤根本运行不起来，不止你这个....

**Comment by dcy421** [comment]
什么错误啊，你来个截图啥的啊，这怎么给你解决啊

**Comment by zhangyi2017** [comment]
数据库错误，忘记截图了。表生成不了，你可以新建个库跑一下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcy421/activiti6-modeler-demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 下午3:24
收件人:&nbsp;"dcy421/activiti6-modeler-demo"<activiti6-modeler-demo@noreply.github.com&gt;;
抄送:&nbsp;"张一"<332672455@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcy421/activiti6-modeler-demo] 运行不了 (#1)





 
什么错误啊，你来个截图啥的啊，这怎么给你解决啊

**Comment by dcy421** [comment]
就差一个配置 true 还 false的区别  database-schema-update: 变成true就好了

**Comment by dcy421** [comment]
check-process-definitions: false
    async-executor-activate: false
    database-schema-update: false
    history-level: full

你清楚一下这几个配置   你就能运行起来了  多学习学习

**Comment by zhangyi2017** [comment]
&nbsp;好的，学习了，主要还是因为我不熟。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "奋斗青年"<notifications@github.com&gt;; 
发送时间: 2020年8月11日(星期二) 下午3:29
收件人: "dcy421/activiti6-modeler-demo"<activiti6-modeler-demo@noreply.github.com&gt;; 
抄送: "张一"<332672455@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcy421/activiti6-modeler-demo] 运行不了 (#1)





 
check-process-definitions: false
 async-executor-activate: false
 database-schema-update: false
 history-level: full
 
你清楚一下这几个配置   你就能运行起来了  多学习学习

**Comment by dcy421** [comment]
嗯  加油
